import os
env = os.environ.get

DEBUG = False
CELERY_ALWAYS_EAGER = False
CACHE = not DEBUG

RESTRICT_IPS = False
ALLOWED_IPS = ['127.0.0.1',]

SITE_TITLE = env('SPENDB_SITE_TITLE', 'SpenDB')
SECRET_KEY = env('SPENDB_SECRET')

SQLALCHEMY_DATABASE_URI = env('SPENDB_DATABASE_URL')
CELERY_BROKER_URL = env('SPENDB_AMQP_URL', env('SPENDB_CLOUDAMQP_URL'))

MAIL_SERVER = env('SPENDB_SMTP_HOST', 'smtp.mandrillapp.com')
MAIL_PORT = int(env('SPENDB_SMTP_PORT', 587))
MAIL_USE_TLS = True
MAIL_USERNAME = env('SPENDB_SMTP_USERNAME', env('SPENDB_MANDRILL_USERNAME'))
MAIL_PASSWORD = env('SPENDB_SMTP_PASSWORD', env('SPENDB_MANDRILL_PASSWORD'))

MAIL_DEFAULT_SENDER = env('SPENDB_MAIL_SENDER', 'SpenDB <info@mapthemoney.org>')

STORAGE_TYPE = 's3' #Alternative: 'file'
STORAGE_PATH = '/a/path/only/valid/if/using/local/file/system'

AWS_KEY_ID = env('SPENDB_AWS_KEY_ID')
AWS_SECRET = env('SPENDB_AWS_SECRET')
AWS_DATA_BUCKET = env('SPENDB_AWS_DATA_BUCKET')

PREFERRED_URL_SCHEME = env('SPENDB_PREFERRED_URL_SCHEME', 'http')
