import os
env = os.environ.get

DEBUG = False
CELERY_ALWAYS_EAGER = False
CACHE = not DEBUG

SITE_TITLE = env('SITE_TITLE', 'SpenDB')
SECRET_KEY = env('SECRET')

SQLALCHEMY_DATABASE_URI = env('DATABASE_URL')
CELERY_BROKER_URL = env('AMQP_URL', env('CLOUDAMQP_URL'))

MAIL_SERVER = env('SMTP_HOST', 'smtp.mandrillapp.com')
MAIL_PORT = int(env('SMTP_PORT', 587))
MAIL_USE_TLS = True
# MAIL_USE_SSL = False
MAIL_USERNAME = env('SMTP_USERNAME', env('MANDRILL_USERNAME'))
MAIL_PASSWORD = env('SMTP_PASSWORD', env('MANDRILL_PASSWORD'))

MAIL_DEFAULT_SENDER = env('MAIL_SENDER', 'SpenDB <info@mapthemoney.org>')

AWS_KEY_ID = env('AWS_KEY_ID')
AWS_SECRET = env('AWS_SECRET')
AWS_DATA_BUCKET = env('AWS_DATA_BUCKET')

PREFERRED_URL_SCHEME = env('PREFERRED_URL_SCHEME', 'http')
