import os
env = os.environ.get

DEBUG = False
ASSETS_DEBUG = False
ASSETS_AUTO_BUILD = False
CELERY_ALWAYS_EAGER = False
CACHE = False

SECRET_KEY = env('SECRET')

SQLALCHEMY_DATABASE_URI = env('DATABASE_URL')
CELERY_BROKER_URL = env('CLOUDAMQP_URL')

MAIL_SERVER = 'smtp.mandrillapp.com'
MAIL_PORT = 587
MAIL_USE_TLS = True
# MAIL_USE_SSL = False
MAIL_USERNAME = env('MANDRILL_USERNAME')
MAIL_PASSWORD = env('MANDRILL_PASSWORD')

MAIL_DEFAULT_SENDER = 'SpenDB <info@mapthemoney.org>'

AWS_KEY_ID = env('AWS_KEY_ID')
AWS_SECRET = env('AWS_SECRET')
AWS_DATA_BUCKET = env('AWS_DATA_BUCKET')

PREFERRED_URL_SCHEME = env('PREFERRED_URL_SCHEME', 'http')
